### PR TITLE
Fixes issue #12 that prevents protoc-gen-micro from importing protobufs in the same folder.

### PR DESCRIPTION
**Pull request by swedishborgie**
I realize this issue (#12) is closed, but we ran across this problem on a project I'm working on. Please feel free to reject this request if not appropriate.

The fix only works if the Go Package name (either by convention or by `option go_package`) are the same between two (or more) protobufs existing in the same directory. I would agree anything else doesn't make sense.

Use Case:

We have a large number of protobufs with which we're using multiple generators to perform various code generation tasks. We have the protobufs split up roughly into three categories: services, rpc messages, and data objects.

We do not want to run all generators on all protobufs, but only the generators that apply directly to the type of protobuf it is. For instance on service protobufs we run gogo and micro; but running micro on another type protobuf would generate a (mostly) empty file. By including required protobufs in the same package we're able to ensure the generated code contains the required components but that we also don't generate code we don't intend to use.

Essentially we're trying to cut down on dead code and reduce the chance that generated code accidentally introduces unexpected behavior into our environment.

The other generators we're using (for instance protoc-gen-gogo) seem to tolerate this situation assuming go_package is set correctly.

### CODE REVIEW

**Comment by asim** [comment]
Does this continue to work in default cases? Can you provide an example of what this fixes?

**Comment by swedishborgie** [comment]
I've tested in my repository and it didn't cause any side effects in protobufs not exhibiting this issue, I believe it should work in all default cases.

I've created a [gist](https://gist.github.com/swedishborgie/ea6b9f0f58aa1b4590713923125035c6) that shows a complete example. But essentially, given a service that looks like this:

    syntax = "proto3";
    option go_package = "myservice";
    import "messages.proto";

    service MyService {
        rpc DoThing(MyMessage) returns (MyMessage) {}
    }

That imports another protobuf like this:

    syntax = "proto3";
    option go_package = "myservice";

    message MyMessage {
        uint32 id = 1;
    }

The protobuf generator will generate code like this:

    import proto "github.com/golang/protobuf/proto"
    import fmt "fmt"
    import math "math"
    import messages "."

    //...

    type MyService interface {
        DoThing(ctx context.Context, in *messages.MyMessage, opts ...client.CallOption) (*messages.MyMessage, error)
    }

Which will not compile, since the package imports itself. The attached pull request changes the output to emit this instead:

    import proto "github.com/golang/protobuf/proto"
    import fmt "fmt"
    import math "math"

    //...

    type MyService interface {
        DoThing(ctx context.Context, in *MyMessage, opts ...client.CallOption) (*MyMessage, error)
    }

**Comment by asim** [comment]
I'll need some others to review this also. Let me ping the community.

**Comment by vtolstov** [comment]
Looks fine, but I'm prefer to have messages in the same file as service, so i not affected by this issue.
For someone it may be useful to split service and message definitions

**Comment by vtolstov** [comment]
Im try to test today and check does it break something or not

**Comment by asim** [comment]
Thanks @vtolstov, appreciate it.

**Comment by vtolstov** [comment]
All compiles and works fine, so i think that it safe for merge.

**Comment by asim** [comment]
Thanks for checking

**Comment by asim** [comment]
Your change has caused this issue https://github.com/micro/protoc-gen-micro/issues/36. I'm reverting for now. I don't have the ability to debug this and need the tooling to remain stable in a constant state.

**Comment by swedishborgie** [comment]
Bummer. Thanks for letting me know; I'll try to take a look at the linked issue today and see if it's something easily fixable.

**Pull request merged**
