### PR TITLE
Create constants for method names

### PR DESCRIPTION
**Pull request by alexbilbie**
This PR adds constants for the RPC method names.

Our use case is that we AWS Lambda functions that call Micro Proxy using client code like this:

```go
// RPCRequest makes an RPC call via the Micro Proxy and returns the response as a byte array which can be cast to a
// protobuf message.
func RPCRequest(
	service string,
	method string,
	data proto.Message,
	timeout time.Duration,
) ([]byte, error) {
	body, _ := json.Marshal(
		struct {
			Service string        `json:"service"`
			Method  string        `json:"method"`
			Request proto.Message `json:"request"`
		}{
			service,
			method,
			data,
		})

	req, _ := http.NewRequest(
		"POST",
		"http://micro-proxy.internal:8081/rpc",
		bytes.NewBuffer(body),
	)
        ...
        ...
```

When we make a request we use the above code like so:

```go
resp, err := RPCRequest(
	client.GetInternalServiceName("order"),
	"InternalOrder.GetOrder", // <- I want to use a constant here
	&pb.GetOrderRequest{
		UserUuid: userUUID.String(),
		OrderKey: orderKey.String(),
	},
	time.Second*3,
)
```

We can easily add type safety to the service name but not the method name that is being called and so rely on copy and pasting which therefore can introduce human error. Also IDEs would auto-suggest a constant too.

Having the constants generated by this PR would remove a log standing niggle at the back of my brain 🙏

### CODE REVIEW

**Comment by asim** [comment]
So I understand what you're trying to do but I'm not sure this makes sense for us. We're code generating calls to the service. Type safety is sort of built from a code generation standpoint because you're expected to use the generated client as opposed to calling method names.

This kind of approach is very ad-hoc. I really only see two paths forward. 

1. Create a go-micro/client which calls the /rpc endpoint of the micro proxy.
2. We provide a more seamless approach to doing this via the proxy

Here's an example gist for the first https://gist.github.com/asim/e16d5e77f5a4b7017faf6342035475e9

**Comment by alexbilbie** [comment]
Perhaps type safety isn't term I'm looking for - maybe developer friendliness is a better term. At the end of the day the bug bear really is that I have to dive through the generated protobuf code to find the exact string to copy and paste - an IDE/text editor will auto-suggest a constant for me.

I appreciate the gist you came up with for the approaches you mentioned above (and the time you spent on it). I suspect I over complicated the use case.

Some other examples where we're copy and pasting the method name string include using the method name in Prometheus metrics and as extra meta data when writing out log lines.

**Comment by asim** [comment]
I think the mistake is to deviate from the existing pattern of development. Go Micro provides the abstractions which we then build on. Proto plus go-micro gives us code generated service definitions. Having to call this via an external method just changes the client required to intia the request and internal translation. It should otherwise behave the same. 

My advice would be to adapt the gist I sent. Personally I'm working towards something like that but more robust. The proto generated code only cares about getting a go-micro client. and the go-micro client is just an interface. So technically replacing it shouldn't be an issue. 

I would get your lambda code to do:

```
client := rpcproxy.NewClient("micro-proxy.internal.com/rpc")
orderService := proto.NewOrderService("order", client)
orderService.GetOrder(OrderRequest)
```

Think of how much cleaner and safe that code becomes. You can rely on the code generation while also using the proxy.

**Comment by alexbilbie** [comment]
Happy to accept your proposal 👍

**Pull request closed without merging**
