### PR TITLE
Fix stutter in service name

### PR DESCRIPTION
**Pull request by shuLhan**
Since not all service can be described by "verb", e.g. "Contact", user
pick the name style used by protobuf documentation, i.e. by adding
"Service" at the suffix.

Commit 50515c2 rename suffix of generated type from XxxClient to
XxxService. If user also use `Service` as the suffix, the generated output
will print `XxxServiceService`.

This commit check if service name has the `Service` suffix before adding
the suffix.

Fix micro/protoc-gen-micro#6 .
Partial fix on micro/protoc-gen-micro#7 .

### CODE REVIEW

**Comment by asim** [comment]
Have you tested this? This fixes nothing for me. It doesn't work. I've checked out your code/branch and it still produces the same code.

**Comment by shuLhan** [comment]
> Have you tested this? This fixes nothing for me. It doesn't work. I've checked out your code/branch and it still produces the same code.

Yes, you may forget to run `go install ./...` on the repository. If you test it on the `example` directory, the example already contains generated code from this commit. But I will try to double check again later.

**Comment by asim** [comment]
I have deleted my protoc-gen-micro binary, checked out your branch, installed it using `go get -u ./...` and `go install ./...` but get the same result

**Comment by asim** [comment]
If my proto defines `service GreeterService` this still generates ServiceService. Not only that but it looks to be adding Client to the end now. This fixes nothing. I think you've misunderstood what the goal here was. It was simply to remove two instances of ServiceService and make it as one. Nothing else.

**Comment by shuLhan** [comment]
> I have deleted my protoc-gen-micro binary, checked out your branch, installed it using go get -u ./... and go install ./... but get the same result

Did you checkout the `dev-shulhan` branch?

I test it again by creating new proto `search.proto` (a copy of greeter but with suffx),
```
syntax = "proto3";

service SearchService {
	rpc Name(SearchRequest) returns (SearchResponse) {}
}

message SearchRequest {
	string name = 1;
}

message SearchResponse {
	repeated string names = 1;
}
```
then run,
```
$ protoc --proto_path=$GOPATH/src:. --micro_out=. --go_out=. search.proto
```
it generated the following `search.micro.go`,
```
// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: search.proto

/*
Package search is a generated protocol buffer package.

It is generated from these files:
	search.proto

It has these top-level messages:
	SearchRequest
	SearchResponse
*/
package search

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for SearchService service

type SearchServiceClient interface {
	Name(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
}

type searchService struct {
	c           client.Client
	serviceName string
}

func NewSearchServiceClient(serviceName string, c client.Client) SearchServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "searchservice"
	}
	return &searchService{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *searchService) Name(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "SearchService.Name", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SearchService service

type SearchServiceHandler interface {
	Name(context.Context, *SearchRequest, *SearchResponse) error
}

func RegisterSearchServiceHandler(s server.Server, hdlr SearchServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&SearchService{hdlr}, opts...))
}

type SearchService struct {
	SearchServiceHandler
}

func (h *SearchService) Name(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.SearchServiceHandler.Name(ctx, in, out)
}
```

**Comment by shuLhan** [comment]
> If my proto defines service GreeterService this still generates ServiceService. Not only that but it looks to be adding Client to the end now.

OK lets discuss this here.

Case 1: Assume that the service name is `Greeter`, we will generated the following interfaces, function, and struct on the same file,

(1.1) a client interface: `GreeterServiceClient`
(1.2) a method to create client: `NewGreeterServiceClient()` that return interface `GreeterServiceClient`
(1.3) server interface: `GreeterServiceHandler`, and
(1.4) server struct: `GreeterService`

Case 2: Service name has suffix `GreeterService`, we will generated the following interfaces, function, and struct on the same file,

(2.1) a client interface: `GreeterServiceClient`
(2.2) a method to create client: `NewGreeterServiceClient()` that return `GreeterServiceClient`
(2.3) a server interface: `GreeterServiceHandler`, and
(2.4) a server struct: `GreeterService`

Now, which point did I need to fix this?

**Comment by asim** [comment]
We switched from generating `GreeterClient` to `GreeterService` to avoid clashing with grpc. We're not generating `GreeterServiceClient` because we don't want the verbosity. There is no need to specify Client.

**Comment by asim** [comment]
Despite removing my $GOPATH/pkg dir and protoc-gen-micro binary I cannot get your branch to work. Have you committed all the code? Are there uncommitted local changes? Are you running it via your branch or building directly out of a patched micro/protoc-gen-micro directory?

**Comment by shuLhan** [comment]
If service have suffix  `GreeterService` and we did not add `Client` it will create a conflict name on server struct,

(2.1) a client interface: GreeterService
(2.2) a method to create client: NewGreeterService() that return GreeterServiceClient
(2.3) a server interface: GreeterServiceHandler, and
(2.4) a server struct: GreeterService <-- conflict with client interface (1.1)

What name do you suggest for generated client interface or server struct?

**Comment by asim** [comment]
Have you actually tested this while generating grpc types as well? You realise there are still conflicts.

**Comment by asim** [comment]
This is the fix I'm looking for. This works without conflict with grpc. It was this simple. 

https://github.com/micro/protoc-gen-micro/pull/9

**Comment by asim** [comment]
I spoke too soon. I also need to resolve method name issues. Not an easy fix.

**Comment by asim** [comment]
Working through the code I can see all the issues your highlighting. This is a very frustrating thing to fix. Not sure what the best move forward is.

**Comment by asim** [comment]
Ok my PR basically resolves all issues. It makes one additional change to turn `GreeterServiceClient` into `NewGreeterService` so we don't clash with grpc.

**Comment by asim** [comment]
My PR does not strip Service entirely. If `FooService` is specified it stays the same. If `Foo` is specified it becomes `FooService`. The code works.

**Comment by shuLhan** [comment]
Ah I see, I will close this PR then.

**Comment by asim** [comment]
Thanks for your effort. Your PR and the ongoing discussion is what helped me come up with a solution.

**Pull request closed without merging**
