### PR TITLE
fix go.mod

### PR DESCRIPTION
**Pull request by zc2638**
Compatible with ```GO111MODULE=on```

### CODE REVIEW

**Comment by asim** [comment]
Your PR deletes literally everything. This seems incorrect?

**Comment by zc2638** [comment]
@asim you can try it.No problem with my test.

**Comment by asim** [comment]
I need a second opinion from @vtolstov

**Comment by vtolstov** [comment]
i don't think that this pr is right. i'm run go mod tidy and see tat go.mod now have
```
module github.com/micro/protoc-gen-micro

require (
        github.com/golang/protobuf v1.3.1
        github.com/hashicorp/go-uuid v1.0.1 // indirect
        github.com/micro/go-micro v1.0.0
        github.com/stretchr/testify v1.3.0 // indirect
        golang.org/x/net v0.0.0-20190327214358-63eda1eb0650
        google.golang.org/grpc v1.19.1
)
```

**Comment by vtolstov** [comment]
thanks, can you squash second change with the first?

**Comment by zc2638** [comment]
If there are many submission records, I can create a new one.

**Comment by vtolstov** [comment]
@asim can you merge with squash?

**Comment by asim** [comment]
Ok so I merged this and the lint replace line was removed so basically it breaks again...

**Comment by vtolstov** [comment]
@asim what is the problem with lint?

**Comment by asim** [comment]
go: github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod: unexpected module path "golang.org/x/lint"

There needs to be the replace statement

**Comment by vtolstov** [comment]
yeah, you right, i have pinned dep to lint so i don't affected by this issue...
@zc2638 can you add another pr with added line in go.mod
replace github.com/golang/lint => golang.org/x/lint v0.0.0-20190301231843-5614ed5bae6f ?

**Comment by asim** [comment]
I fixed it. Don't worry.

**Pull request merged**
